# Generated by Django 4.2.7 on 2023-12-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='img/gallery')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('time', models.DateField(auto_now=True)),
                ('meta', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='img/news')),
                ('caption', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/teacher')),
                ('teach', models.CharField(choices=[('Menggambar dan Mewarnai', 'Menggambar dan Mewarnai'), ('Melukis', 'Melukis'), ('Kaligrafi', 'Kaligrafi')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=20)),
                ('says', models.CharField(max_length=200)),
            ],
        ),
    ]
